import style from './page.module.scss'

const page = () => {
  return (
    <div className="content">
      <div className={`${style.about_text} content__container`}>
        <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta nemo nulla doloremque et, omnis voluptatem minima nam totam vel dicta suscipit, delectus doloribus nesciunt reiciendis neque? Inventore quia rem expedita!
          Delectus nam architecto repudiandae exercitationem praesentium iste. Eius ad, alias odio natus hic repellat minus dolor quidem a quibusdam explicabo nemo cumque earum culpa facere deleniti officiis laborum! Accusamus, quae!
          Autem sint vitae et dolore architecto aspernatur saepe ea pariatur odio animi dolor, blanditiis eius perferendis voluptatum iste vero. Assumenda accusamus ipsam quos eum numquam nobis. Nam harum itaque id.
          Neque officia eveniet provident rem dolore veritatis ex ipsum hic aut tempore voluptas deleniti fugit, quae temporibus molestias nostrum, assumenda quasi debitis cum in officiis voluptates molestiae. Voluptatem, consequuntur magni?
          Dolor maiores consequatur eligendi ipsam excepturi necessitatibus corporis obcaecati, nam enim soluta, beatae veniam, eveniet asperiores aperiam iure ut cupiditate vitae sapiente repellendus dolore! Modi eveniet quia porro! Voluptas, consectetur.
          Rerum quia temporibus consequuntur dolorem dignissimos, amet optio nemo iure, est, labore corrupti sunt rem quam voluptatum molestias soluta dolores eveniet. Aut eveniet assumenda autem exercitationem perspiciatis placeat id magnam.
          Ipsum itaque adipisci doloribus explicabo hic sequi, voluptatibus aperiam blanditiis est optio ducimus obcaecati error numquam alias sapiente, inventore quo mollitia? Reprehenderit quas minus exercitationem qui asperiores quae! Reiciendis, atque.
          Dolorum veniam similique perferendis alias ab voluptate inventore maxime et possimus eaque quaerat aperiam, consequuntur velit quasi rerum aliquam! Pariatur autem vero exercitationem aspernatur libero harum deserunt atque ullam repellendus!
          Quaerat adipisci quae unde labore non quisquam, totam sit expedita quasi animi eveniet provident veniam, deserunt ut tempore velit reprehenderit obcaecati recusandae asperiores harum quos. Optio dolorem magni aliquid omnis.
          Consequatur, nisi! Optio totam fugit impedit quas omnis provident. Quaerat, optio nesciunt? Expedita ea doloribus ex ducimus rerum quisquam ipsa omnis assumenda, dolores rem eum at consequuntur, dolor aliquid sit?
          Impedit minima officiis dolores reprehenderit praesentium delectus totam soluta! Obcaecati velit animi officia dolore ullam error placeat enim expedita sunt quis architecto sapiente alias, praesentium deleniti sint id nulla repellendus.
          Sapiente voluptatum alias vitae autem atque odit aliquam quaerat distinctio, eligendi adipisci debitis ipsam dolorum eum accusantium omnis dolores voluptates reprehenderit laudantium eaque optio doloribus dicta. Soluta, in. Optio, ab?
          Eius quisquam perferendis, quae veniam magni dolore saepe velit incidunt tempora dolor iste non adipisci repudiandae officiis voluptatibus vitae rerum magnam quaerat, iure labore numquam eum? Quidem nesciunt fuga a?
          Error sit saepe possimus cumque! Dolore, ullam, beatae nobis commodi itaque temporibus consequatur ea tempora obcaecati porro nulla, dignissimos reprehenderit? Sint repudiandae nam mollitia! Repellendus odio vel accusantium distinctio esse!
          Molestias laboriosam quo nobis animi suscipit quia iusto exercitationem laudantium, inventore quas error voluptatibus tenetur illo, consequatur accusamus maiores neque odit possimus architecto soluta? Commodi ut eum quibusdam unde! Doloribus.
          Odit adipisci officiis ullam accusantium eaque repellat repellendus atque numquam nulla magni voluptate eum id architecto tempora reprehenderit quidem tempore, excepturi laboriosam impedit obcaecati facere distinctio. Deserunt rem corrupti suscipit.
          Quas iusto, quisquam sequi eveniet excepturi libero voluptatem alias amet laboriosam accusantium perferendis porro vero quibusdam expedita voluptate odio autem aliquam. Atque corrupti nisi tempora harum incidunt itaque, nam voluptates.
          Ut, tenetur, minus et natus consequuntur accusantium culpa quo vero dolores incidunt ipsum est corrupti sapiente dignissimos a non amet adipisci dolor magni, deserunt eveniet exercitationem officia fugiat. Harum, asperiores.
          Possimus perspiciatis ab maiores reprehenderit quis exercitationem quia amet! Iste, qui voluptatibus non aliquid cupiditate ipsam deserunt ratione in minima officia similique, laudantium tenetur placeat repellat consectetur tempora beatae porro?
          Hic omnis quibusdam tempora aliquid harum magnam ratione. Voluptatum praesentium, molestias modi repellendus incidunt rerum veniam at illum esse ratione delectus, consequuntur temporibus magni possimus quas! Quidem obcaecati soluta doloremque?
          Minus nobis tempore esse deserunt sint! Unde, hic autem fuga quae odit, minima exercitationem molestias, repellendus vero nobis odio dolorum neque blanditiis facere aliquid laborum ipsam qui harum voluptates! Excepturi.
          Rem nesciunt voluptatum veniam sequi, ducimus vitae ipsam inventore iusto eum consequatur explicabo architecto accusamus voluptatibus ex ullam veritatis, iure aliquam. Laborum aut, odit nisi neque asperiores dolor aspernatur beatae.
          Deleniti quis, quae cumque officia delectus perspiciatis quisquam harum asperiores necessitatibus culpa placeat, nulla maxime tenetur aspernatur repellendus totam iure amet sint incidunt architecto eum quaerat at. Iusto, quae aliquid?
          Cum molestias ad blanditiis dicta delectus natus velit corrupti maxime impedit obcaecati dolorem alias quam, accusamus necessitatibus debitis ullam molestiae reiciendis perferendis a enim quia voluptas mollitia commodi eius. Sequi.
          Quibusdam, eum sunt autem aut, culpa numquam dignissimos deleniti sint itaque quasi voluptates. Molestiae, ut corrupti, eos aliquam saepe ad tempora nihil cumque commodi fugit illum eum dignissimos tenetur suscipit!
          Id maxime quidem dolorum vel iusto, placeat ducimus voluptates reiciendis. Modi ipsa nemo ab quod nobis. Porro minus aliquam, facere rerum sunt aperiam ut rem, quidem amet dolores, dolore aspernatur?
          Sed quasi rerum exercitationem suscipit reprehenderit ducimus mollitia culpa quam laudantium minus, inventore ex laborum neque vitae qui odio alias unde provident temporibus modi corrupti autem praesentium incidunt accusamus. Eos?
          Ut corrupti voluptatem, nam consequuntur quisquam asperiores nesciunt! Quod sed obcaecati eaque. Vitae facilis cum asperiores! Soluta iusto sequi beatae quam, modi totam laborum possimus ad sapiente, eaque corporis nesciunt!
          Magni recusandae repellendus eveniet tenetur, dicta voluptatum provident perspiciatis maxime ea quis iusto ad aliquam, ut tempora distinctio laboriosam excepturi ullam vel! Qui, eaque fugit temporibus possimus similique praesentium suscipit?
          Assumenda eum totam odio aut corrupti reprehenderit nihil tempora ratione, fugit sint tenetur natus enim maxime non, qui quos hic deserunt! Laboriosam, quidem expedita corporis ad sit nisi! Dolore, sed?
          Suscipit ab voluptatem natus inventore, nam sed illum hic tempora dolorum temporibus, ullam reiciendis aut accusantium quasi pariatur provident sapiente omnis. Praesentium quaerat similique, suscipit excepturi nulla eius maiores deserunt.
          Error expedita similique in illo! Voluptatem at nostrum ullam eaque vel iusto obcaecati quo laboriosam ad laudantium, expedita ea autem repellat sapiente eum illo a voluptas eos. Temporibus, deserunt minima!
          Laboriosam, debitis. Labore corrupti doloremque accusantium eligendi cupiditate harum, mollitia, assumenda praesentium aut dignissimos velit vel placeat quod aspernatur quaerat ipsam eveniet odio ipsa sapiente! Atque ea asperiores itaque! Velit.
          Nihil eum quia hic error ex nemo dolore quae recusandae accusantium cupiditate unde doloremque similique voluptas dolores amet, quam maiores expedita facere nisi fugiat consequatur reprehenderit dicta! Animi, expedita sapiente.
          Optio eos sequi aperiam pariatur, cumque ullam quae aut at quaerat, veritatis doloribus labore vero, animi sed officia alias a veniam. Incidunt optio ipsam deleniti nisi sed repellat voluptatum harum?
          Aut est perspiciatis itaque aspernatur, id esse nesciunt omnis, quae odit nemo molestiae ex expedita delectus sed. Perspiciatis iste officiis voluptatum earum! Accusantium architecto facere omnis reiciendis eveniet, minus corrupti!
          Id incidunt dignissimos quibusdam, adipisci dolorem quidem aut cupiditate nemo recusandae nulla, vel natus quas. Pariatur eveniet beatae velit. Voluptas commodi quia tempore maiores ipsa maxime error minima ea similique?
          Labore, officia praesentium! Blanditiis repellat perferendis veritatis nulla excepturi eum velit aliquid unde nesciunt! Modi porro earum iusto ullam accusantium soluta quos, iure a reprehenderit, dolores pariatur est dicta necessitatibus?
          Magnam, nulla dicta animi saepe sit esse sapiente. Fugiat voluptatibus ex reprehenderit voluptatum commodi molestias libero ea soluta totam, blanditiis optio cupiditate fuga deserunt placeat debitis quisquam! Nihil, ea soluta.
          Necessitatibus ut dignissimos nisi veritatis voluptate. Suscipit eum omnis alias quibusdam mollitia id hic laboriosam explicabo, quos nam quam ipsum consequuntur quo blanditiis totam aliquid repudiandae! Animi totam ipsam ut?
          Nesciunt, accusantium blanditiis necessitatibus aliquam corporis modi in ab tempore nisi iusto eligendi quae esse maiores, quam debitis delectus ipsum adipisci quasi! Nulla, iusto veniam neque nostrum cupiditate error tenetur?
          Consequuntur saepe non distinctio fugit unde fuga delectus, provident eligendi, tenetur voluptatibus doloremque perspiciatis? Doloremque illo voluptatibus maiores quo placeat tenetur, nihil libero ipsam totam, ducimus repellendus explicabo ex culpa.
          Facere culpa architecto aliquid similique vero autem odio possimus, magnam in accusamus quis et modi nobis a consequatur sunt voluptate? Rem eveniet corporis autem delectus repudiandae ipsam accusamus quasi non.
          Beatae dolorem dicta iusto praesentium aperiam sint aspernatur reiciendis fugiat temporibus tempora unde vitae voluptas fuga suscipit, modi sed vel id tenetur placeat nisi nostrum veniam quod debitis quis. Illum.
          Maxime ratione consequatur placeat incidunt officiis vel culpa molestias voluptatibus repellendus modi perferendis cupiditate maiores obcaecati optio, delectus necessitatibus quibusdam voluptatem numquam? Ullam obcaecati distinctio eos cupiditate doloremque at atque.
          Nesciunt esse maxime facilis porro aliquam, molestiae magnam praesentium, tempora perspiciatis aut neque repellendus error sapiente dolorum voluptate quasi animi, iusto quidem! Error cupiditate illo repellendus laudantium atque commodi molestiae?
          Quasi quod iusto quidem vero, optio maiores dicta. Optio veritatis atque minus explicabo in illum officiis suscipit ex laborum obcaecati labore quia maxime non corporis praesentium molestias, quas, distinctio architecto.
          Iure cumque quis ex, velit non hic, amet neque, consequatur eum maiores animi optio praesentium? Eos, ipsam? Suscipit adipisci numquam laboriosam repellat repellendus! Earum esse praesentium non, repudiandae saepe corrupti.
          Vel aspernatur numquam, quod deleniti rem facilis corrupti hic libero voluptatum illum blanditiis alias non maxime sint reiciendis cupiditate quibusdam maiores quos consequuntur modi nostrum, incidunt quas. Rerum, ullam delectus.
          Aliquam necessitatibus iure omnis veritatis, rem eligendi asperiores hic corporis. Harum fuga ab, tempore porro odit id maiores repellendus fugiat praesentium nobis dolores explicabo voluptatum, tempora distinctio. Molestiae, saepe velit?
          Porro doloremque fugiat reprehenderit quae earum tenetur temporibus autem tempora voluptas impedit. Mollitia sapiente repellendus doloribus consequuntur natus nostrum libero nihil quidem quod? Doloremque a accusamus, minus adipisci ipsum vitae.
          Modi dolore consequuntur quisquam maxime atque sit omnis mollitia aliquid deserunt libero labore sunt quaerat nemo nobis soluta cum nesciunt at porro eaque cupiditate obcaecati sint, quae nisi quod? Recusandae.
          Laborum libero commodi eaque quod sunt quae consequatur quaerat unde voluptatibus distinctio corporis iure, asperiores earum temporibus quibusdam ducimus iste maiores architecto error dicta mollitia deserunt debitis! Illo, voluptatem optio.
          Voluptate sint ipsa, aliquid possimus maxime quas, expedita maiores dolorem rem consequuntur unde accusantium ullam nam quidem fugit voluptatem nobis! Consequatur, itaque! Repudiandae libero debitis blanditiis, tenetur sed asperiores quisquam!
          Ducimus neque corporis doloremque animi? Qui harum iure aliquam accusantium voluptates eaque consequatur, perspiciatis ab deserunt, temporibus quo earum quaerat, dolore architecto officiis nulla cumque facere repudiandae a suscipit dolorum.
          Eveniet natus non doloribus ducimus id mollitia officia porro deleniti et animi! Repellendus quo quas expedita incidunt cum tenetur ipsam quia? Aliquam iure ducimus voluptas qui velit ipsam explicabo molestias.
          Est amet accusantium minus itaque ea, qui natus dicta doloremque eveniet veniam aperiam voluptatibus et tempore mollitia harum cumque perferendis minima nesciunt quam officia! Ipsam voluptates hic eum alias beatae.
          Ea temporibus magni maiores veniam atque aut at provident eius repudiandae blanditiis? Ullam architecto ratione, maiores sit excepturi nulla cumque illo est impedit autem ab dolore, voluptate dolorem, ducimus ipsum.
          Ducimus omnis quaerat adipisci consectetur molestiae harum voluptatem ex minima deleniti dicta nemo, ratione optio. Eos magnam expedita culpa, natus animi voluptates vitae omnis recusandae iusto tempora autem assumenda rem.
          Totam reprehenderit veritatis eveniet aspernatur cumque aliquid exercitationem quod, voluptatem architecto numquam distinctio asperiores nostrum fuga illum! Facere quis, sint pariatur doloremque voluptates maiores deleniti corporis consequuntur. Sint, similique ut.
          Deleniti autem amet veniam iusto necessitatibus. Itaque quaerat, error fugit officia maxime esse consequuntur sed molestiae, quae beatae cupiditate vel voluptates deleniti expedita veritatis dolor neque accusamus qui perspiciatis ex!
          Ab et, atque totam soluta maiores nobis veniam officiis ex earum. Odit sequi eum, porro aut molestiae obcaecati illo facere tempora quas, sed recusandae culpa explicabo! Quod possimus enim nemo!
          Beatae pariatur provident enim obcaecati tenetur placeat doloremque voluptatem commodi cum incidunt totam, fuga veniam doloribus? Sed ipsam dicta fugit dolor laborum totam repellat, ipsum suscipit, ducimus, eius labore voluptates!
          Reiciendis beatae quisquam maxime in deleniti cum qui dolore laborum ex voluptas corrupti tempora, consequatur quos cumque deserunt id accusantium. Inventore veniam itaque cupiditate quos iusto vitae voluptate error exercitationem!
          Consequuntur maiores quos est quam, quidem velit id vel! Eligendi incidunt natus, accusantium commodi aliquid reprehenderit? Odit error eveniet magnam deleniti accusamus ut, commodi excepturi in! Assumenda aperiam ab velit.
          Nobis in quibusdam quaerat soluta odio commodi doloribus ipsum iste dolor consectetur. Quam at perferendis tenetur, voluptates odit nemo iste voluptate ipsam inventore tempore qui quibusdam ea a dolores fugiat.
          Atque incidunt at exercitationem aspernatur quaerat? Ad omnis optio voluptas consequuntur deleniti non quo vitae culpa fuga. Non, possimus consectetur facere perferendis obcaecati sunt culpa quaerat similique voluptates voluptatum officia!
          Officiis necessitatibus eaque officia dolores facilis accusamus incidunt cumque atque? Dolorem quod excepturi natus hic sit nam laborum, repellendus veniam beatae soluta deserunt, nemo cupiditate delectus consequuntur id quos aperiam.
          Labore delectus aut odio consequatur dignissimos inventore qui quae, id temporibus fugiat, sint laborum quas ipsa quasi exercitationem at voluptas praesentium numquam quam. Inventore, expedita amet atque ea voluptates vero?
          Porro quasi omnis laborum beatae sint voluptate nulla vitae, ab minima hic voluptas quis obcaecati? Libero molestias cupiditate, a ipsa ullam nam dignissimos enim, nobis et impedit, est tenetur dicta.
          Recusandae temporibus sapiente aliquam. Ipsa velit debitis eligendi laudantium facilis dolorem atque repudiandae, molestiae qui id enim magnam incidunt quis ex ipsam ullam ab nostrum officia dignissimos maxime quia iusto?
          Porro iste, totam recusandae ducimus, voluptate eius dolorem ad, sunt possimus deleniti perferendis suscipit nostrum similique architecto voluptatum eos? Quibusdam incidunt ullam aliquam sed laboriosam sint mollitia nisi eius fugiat.
          In nostrum blanditiis quos iste reprehenderit velit! Suscipit consectetur dolorum minima repellendus assumenda, dolore pariatur voluptas aspernatur in quam numquam, ab, excepturi tempora sunt ad vero facere? Atque, laudantium eos.
          Doloremque vel pariatur placeat ullam dolores reiciendis, ducimus, qui fuga, reprehenderit cum molestiae. Expedita sint deleniti nemo placeat omnis, maxime architecto numquam, est mollitia, atque ullam at possimus tempore? Commodi.
          Provident quo quos quis reprehenderit beatae corrupti sapiente officiis magni? Quae distinctio, recusandae non consectetur mollitia optio commodi voluptatem natus aliquam autem eius adipisci a, alias accusantium. Est, vero odit.
          Iusto aperiam similique nemo, deserunt ab, ratione doloribus accusamus quisquam quia recusandae consectetur? Deleniti, voluptate! Magni recusandae reiciendis hic id dolore officiis officia itaque provident beatae, earum sit exercitationem quidem!
          Asperiores dignissimos veniam explicabo, ad temporibus perferendis doloremque blanditiis. Totam ut quibusdam inventore officia similique minus, excepturi eligendi architecto nesciunt et iste assumenda aspernatur voluptatem atque maxime facere quasi repellat?
          In quae cum voluptatem adipisci, vero eaque, modi at voluptatum ut aut nihil tempore vitae, ducimus aspernatur autem atque. Eos quo cupiditate neque modi eius maiores, ullam assumenda rem tempore.
          Nihil aliquam nesciunt dolore provident minima! Officiis placeat vitae doloribus quo! Beatae delectus voluptatem corrupti ea, debitis cum asperiores alias exercitationem repudiandae nostrum facilis sunt, consectetur iste fugiat fugit a.
          Laudantium rerum veniam necessitatibus maiores dolores molestiae, impedit corrupti itaque sint eligendi corporis repellat placeat, eum aliquam, ipsum odit consectetur explicabo voluptatum quaerat magnam expedita. A id et veritatis facere.
          Suscipit, optio? Temporibus cumque consectetur, libero reiciendis soluta aperiam consequatur expedita ipsa fuga quis, et praesentium quam provident, dolore omnis obcaecati beatae odio necessitatibus esse laborum pariatur tenetur adipisci laboriosam.
          Vitae delectus corrupti ipsa officia accusantium. Atque, odio? Quo molestiae deserunt inventore illo eos perspiciatis voluptate voluptatem dolore ducimus placeat, praesentium, fugit eaque beatae modi! Temporibus culpa ipsa at voluptatum.
          Pariatur natus doloribus veritatis quasi sapiente assumenda dicta. Distinctio facilis earum tenetur, quidem reiciendis porro esse, maxime ipsa sed eos nihil dolor omnis exercitationem ab assumenda. Obcaecati inventore quasi neque.
          Sequi iure libero, necessitatibus recusandae error minus labore adipisci, nam deleniti minima culpa, pariatur temporibus odio ipsa tempora. Expedita esse, soluta dolorum temporibus placeat animi similique aperiam molestias voluptatum minima!
          Laudantium, libero! Omnis voluptate quaerat voluptates mollitia architecto ipsum pariatur delectus, dolorum, qui dignissimos iure molestias temporibus soluta sunt ab unde deleniti quae dolor explicabo commodi perferendis nisi assumenda. Iste.
          Ut obcaecati reprehenderit maxime rerum ratione voluptatum, accusamus nobis excepturi doloribus voluptate rem, quod non assumenda consectetur blanditiis eaque consequatur. Dolore voluptate id veniam beatae porro consectetur delectus ea recusandae!
          Assumenda at asperiores quis mollitia. Maxime molestiae numquam porro voluptatibus quisquam quibusdam illo corrupti laboriosam vero debitis expedita eius, sunt assumenda suscipit a reiciendis recusandae consequatur error temporibus! Nobis, dolor.
          A nemo qui dicta, sequi maxime nihil voluptatibus repellat possimus tempora nulla inventore recusandae hic adipisci cumque quasi totam expedita similique culpa sapiente dolorum consequuntur fuga in. Odit, aperiam aliquid.
          Placeat voluptatem, iusto temporibus quod eligendi magni enim molestias tenetur numquam rem. Quas unde eaque tempore! Blanditiis eligendi magnam pariatur quia voluptatibus culpa cupiditate, quo quidem quisquam architecto molestiae praesentium.
          Explicabo excepturi nihil aut eveniet ullam officiis quidem, rerum facere deleniti temporibus animi quis velit perferendis quo tempora vel. Eligendi atque cupiditate expedita iusto ex nobis accusantium quaerat! Molestias, enim!
          Ullam asperiores velit adipisci enim id totam at quasi! Vitae porro omnis reiciendis culpa, sunt cumque distinctio dignissimos? Rem ipsa obcaecati consectetur ea harum nam, distinctio officia non reprehenderit culpa?
          Consectetur illo adipisci fugit minima ducimus repellendus ipsam asperiores dolores. Voluptatibus quisquam a laboriosam aut, atque maxime at nulla corporis excepturi maiores rem! Delectus a corporis rerum recusandae! Debitis, doloribus?
          Veritatis laboriosam impedit tempora fugiat, assumenda itaque eum voluptate quis tempore eveniet ipsam saepe aut ipsa voluptatum vero amet quos numquam natus. Veniam fugit odio dicta voluptas, quasi atque hic?
          Velit unde ipsa est, nostrum odio quidem voluptatum, minus id quae culpa, dicta fugit reprehenderit fuga! At similique fuga repellendus ratione nam eius, odit non tempore. At vero odio facere.
          Aspernatur aliquid, eveniet inventore enim pariatur cupiditate ratione fuga dolor sit laborum, distinctio, est reprehenderit? Rerum voluptates doloremque ratione harum iure? Sequi consequatur fuga sapiente maxime vel in, tempora rem?
          Sequi, in, commodi ipsa nulla ipsum earum dignissimos, blanditiis veritatis facilis ab amet! Reprehenderit iste ex sapiente natus quos pariatur illum vitae facilis beatae tempora, aliquid repellat saepe a magni?
          Deserunt placeat laboriosam recusandae, harum assumenda voluptatum id earum aliquam provident vitae repellendus ullam fuga nesciunt enim error aliquid nostrum aut pariatur modi perferendis explicabo unde exercitationem ducimus suscipit. Quia?
          Aliquid facere fugiat dolore sit, dicta vel optio quasi placeat fuga est mollitia corporis dolorem dignissimos ut voluptatum, cum quidem, suscipit doloribus autem explicabo. Officia praesentium ipsum delectus quos at!
          Distinctio officia doloribus iure doloremque est harum eos expedita exercitationem ad quos labore illum explicabo, incidunt dolore delectus facilis. Quidem culpa eum aliquam tempora, consequatur alias recusandae necessitatibus quas est?
          Inventore voluptatem totam dolore iusto rerum architecto doloribus? Nesciunt eaque facilis, sit, sed error voluptatem sapiente, est id corporis et exercitationem distinctio quam blanditiis? Dignissimos ipsa aliquid consequuntur porro delectus.</span>
      </div>
    </div>
  )
}

export default page;
